#!/bin/sh
# postinst script for clinic

set -e

. /usr/share/debconf/confmodule

if [ "$1" = "configure" ]; then

	db_version 2.0

	# The following only on a new install
	if [ "$2" = "" ]; then
			db_get khomsn-klinic-suite/setup-username
			setup_username=${RET:-admin}
			
			db_get khomsn-klinic-suite/setup-password
				setup_password=${RET}
			echo "<?php

define (\"DB_USER\", \"$setup_username\"); // set database user //change me here!
define (\"DB_PASS\", \"$setup_password\"); // set database password //change me here!
" > /etc/khomsn/klinic/dbuspwd.php
			db_reset khomsn-klinic-suite/setup-username || true
			db_reset khomsn-klinic-suite/setup-password || true

	fi

fi

rm -rf /var/cache/debconf/*

ln -sf /etc/khomsn/klinic/dbuspwd.php /var/www/html/config/dbuspwd.php
ln -sf /etc/khomsn/klinic/emailserver.php /var/www/html/config/emailserver.php
ln -sf /etc/khomsn/klinic/recaptchakey.php /var/www/html/config/recaptchakey.php

chmod 0640 /etc/khomsn/klinic/dbuspwd.php
chmod 0640 /etc/khomsn/klinic/emailserver.php
chmod 0640 /etc/khomsn/klinic/recaptchakey.php
chown root:www-data /etc/khomsn/klinic/dbuspwd.php
chown root:www-data /etc/khomsn/klinic/emailserver.php
chown root:www-data /etc/khomsn/klinic/recaptchakey.php

chmod 0755 /var/www/html/libs/PHPMailer-master
chmod 0755 /var/www/html/libs/fpdf181
# make directory for picture

if [ -d "/var/www/html/image" ]; then
  # Control will enter here if $DIRECTORY exists.
    chown www-data:www-data /var/www/html/image
    chmod 0755 /var/www/html/image
    chown www-data:www-data /var/www/html/image/*
    chmod 0755 /var/www/html/image/*
    
fi

if [ ! -d "/var/www/html/image" ]; then
    mkdir /var/www/html/image
    chown www-data:www-data /var/www/html/image
    chmod 0755 /var/www/html/image
  # Control will enter here if $DIRECTORY doesn't exist.
fi

if [ -d "/var/www/html/image/wallpaper" ]; then
  # Control will enter here if $DIRECTORY exists.
    chown www-data:www-data /var/www/html/image/wallpaper
    chmod 0755 /var/www/html/image/wallpaper
    chown www-data:www-data /var/www/html/image/wallpaper/*
    chmod 0755 /var/www/html/image/wallpaper/*
    
fi

if [ ! -d "/var/www/html/image/wallpaper" ]; then
    mkdir /var/www/html/image/wallpaper
    chown www-data:www-data /var/www/html/image/wallpaper
    chmod 0755 /var/www/html/image/wallpaper
  # Control will enter here if $DIRECTORY doesn't exist.
fi

if [ -d "/var/www/html/public/avatars" ]; then
  # Control will enter here if $DIRECTORY exists.
    chown www-data:www-data /var/www/html/public/avatars
    chmod 0755 /var/www/html/public/avatars
    chown www-data:www-data /var/www/html/public/avatars/*
    chmod 0755 /var/www/html/public/avatars/*
fi

if [ ! -d "/var/www/html/public/avatars" ]; then
    mkdir /var/www/html/public/avatars
    chown www-data:www-data /var/www/html/public/avatars
    chmod 0755 /var/www/html/public/avatars
  # Control will enter here if $DIRECTORY doesn't exist.
fi

if [ ! -d "/var/www/html/public/ptimages" ]; then
    mkdir /var/www/html/public/ptimages
    chown www-data:www-data /var/www/html/public/ptimages
    chmod 0755 /var/www/html/public/ptimages
  # Control will enter here if $DIRECTORY doesn't exist.
fi

exit 0
