<script>
$(document).ready(function(){
	$("#lbn").autocomplete({
        source:"../../libs/lbnlist.php",
        minLength:1,
        autoFocus:true
    });
	$("#lsn").autocomplete({
        source:"../../libs/lslist.php",
        minLength:1,
        autoFocus:true
    });
	$("#lsp").autocomplete({
        source:"../../libs/lsplist.php",
        minLength:1,
        autoFocus:true
    });
});
</script>
