<script type="text/javascript">
$(document).ready(function(){
    $("#pref").autocomplete({
        source:'../../libs/prefixlist.php',
        minLength:1,
        autoFocus:true
    });
    $("#fname").autocomplete({
        source:'../../libs/namelist.php',
        minLength:1,
        autoFocus:true
    });
    $("#lname").autocomplete({
        source:'../../libs/lnamelist.php',
        minLength:1,
        autoFocus:true
    });
    $("#htel").autocomplete({
        source:'../../libs/plinelist.php',
        minLength:1,
        autoFocus:true
    });
    $("#mtel").autocomplete({
        source:'../../libs/cellplist.php',
        minLength:1,
        autoFocus:true
    });
    $("#cid").autocomplete({
        source:'../../libs/cidlist.php',
        minLength:1,
        autoFocus:true
    });
});
</script>
